#
# Crowding configuration
#
project_id: '460074'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

#
# Files configuration
#
files: [
  # JSON translation files
  {
    source: '/i18n/en/**/*',
    translation: '/i18n/%two_letters_code%/**/%original_file_name%',
  },
  # Docs (Current) Markdown files
  {
    source: '/docs/**/*',
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%',
  },
  # Docs (Versioned) Markdown files
  {
    source: '/versioned_docs/**/*',
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%',
  },
]